version: "3.5"
services:
  spring-boot:
    image: spring-boot
    build:
      context: .
    ports:
      - "8083:8083"
     # - "5005:5005"
    volumes:
       - ${APPLICATION_ROOT_FOLDER}:/usr/src/mymaven
      #- ${MAVEN_SETTINGS_FOLDER}:/root/.m2   # comment this line if you do not want to use you local maven settings or if you do not have a local maven installed
